QUERY_1 = """
SELECT *
FROM (
WITH DADOS_CONTA_AMB
  AS
  (SELECT DISTINCT X.CD_REG_AMB
        , X.CD_ATENDIMENTO
        , Y.DT_LANCAMENTO_FINAL DT_INICIO
        , Y.DT_LANCAMENTO_FINAL DT_FINAL
        , X.DT_FECHAMENTO
        , Y.CD_REMESSA
        , Y.CD_MULTI_EMPRESA
        , Y.VL_TOTAL_CONTA
        , Y.SN_FECHADA
        , Y.CD_CONVENIO
     FROM DBAMV.ITREG_AMB X
     INNER JOIN DBAMV.REG_AMB Y ON X.CD_REG_AMB = Y.CD_REG_AMB
     WHERE Y.CD_CONVENIO = 304 /*IN (SELECT Z.CD_CONVENIO
                                FROM DBAMV.CONVENIO Z
                                WHERE Z.TP_CONVENIO = 'P')*/
  )

SELECT  'REG_FAT' TIPO_CONTA
  , Decode(ATENDIME.TP_ATENDIMENTO,'I','INTERNACAO','U','URGENCIA','A','AMBULATORIAL','E','SADT') TP_ATENDIMENTO
  , CASE
      WHEN ATENDIME.CD_CONVENIO <> REG_FAT.CD_CONVENIO
      THEN 'CONTA EXTRA'
      ELSE 'PARTICULAR'
    END TIPO
  , ORI_ATE.DS_ORI_ATE
  , SETOR.NM_SETOR
  , REG_FAT.CD_REG_FAT CONTA
  , to_char(ATENDIME.DT_ATENDIMENTO,'dd.mm.yyyy hh24:mi:ss') DT_ATENDIMENTO
  , to_char(ATENDIME.DT_ALTA,'dd.mm.yyyy hh24:mi:ss') DT_ALTA
  , to_char(REG_FAT.DT_INICIO,'dd.mm.yyyy hh24:mi:ss') DT_INICIO
  , to_char(REG_FAT.DT_FINAL,'dd.mm.yyyy hh24:mi:ss') DT_FINAL
  , to_char(REG_FAT.DT_FECHAMENTO,'dd.mm.yyyy hh24:mi:ss') DT_FECHAMENTO
  , REG_FAT.CD_REMESSA
  , MULTI_EMPRESAS.APELIDO CD_MULTI_EMPRESA
  , REG_FAT.CD_ATENDIMENTO
  , REG_FAT.VL_TOTAL_CONTA
  , REG_FAT.SN_FECHADA
  , CON_REC.CD_CON_REC
  , ITCON_REC.CD_ITCON_REC
  , to_char(ITCON_REC.DT_PREVISTA_RECEBIMENTO,'dd.mm.yyyy hh24:mi:ss') DT_PREVISTA_RECEBIMENTO
  , ITCON_REC.TP_QUITACAO
  , ITCON_REC.VL_DUPLICATA
  , ITCON_REC.VL_SOMA_RECEBIDO
  , Nvl(ITCON_REC.VL_DUPLICATA,0) - Nvl(ITCON_REC.VL_SOMA_RECEBIDO,0) VL_EM_ABERTO
  , Round(Nvl(REG_FAT.DT_FECHAMENTO, SYSDATE) - Nvl(REG_FAT.DT_FINAL, SYSDATE),2) DIAS_DTFINAL_FECHAMENTO
  , Round(Nvl((SELECT Max(PROTOCOLO_DOC.DT_ENVIO)
      FROM DBAMV.PROTOCOLO_DOC
      INNER JOIN DBAMV.IT_PROTOCOLO_DOC ON PROTOCOLO_DOC.CD_PROTOCOLO_DOC = IT_PROTOCOLO_DOC.CD_PROTOCOLO_DOC
      WHERE IT_PROTOCOLO_DOC.CD_REG_FAT = REG_FAT.CD_REG_FAT
      AND PROTOCOLO_DOC.CD_SETOR_DESTINO = 2
      AND IT_PROTOCOLO_DOC.CD_DOCUMENTO_PROT = 3),SYSDATE) - Nvl(REG_FAT.DT_FECHAMENTO, SYSDATE),2) DIAS_FECHAMENTO_MOVDOC
  , CASE
      WHEN ITCON_REC.DT_PREVISTA_RECEBIMENTO IS NULL
      THEN 'SEM RECEBIMENTO AGENDADO'
      WHEN (SYSDATE - ITCON_REC.DT_PREVISTA_RECEBIMENTO) > 30
      THEN 'INADIMPLENTE'
      ELSE 'PAGAMENTO AGENDADO'
     END STATUS_PAGTO
  , ATENDIME.CD_PACIENTE
FROM DBAMV.ATENDIME
INNER JOIN DBAMV.ORI_ATE ON ATENDIME.CD_ORI_ATE = ORI_ATE.CD_ORI_ATE
INNER JOIN DBAMV.SETOR ON ORI_ATE.CD_SETOR = SETOR.CD_SETOR
INNER JOIN DBAMV.REG_FAT ON ATENDIME.CD_ATENDIMENTO = REG_FAT.CD_ATENDIMENTO
INNER JOIN DBAHMD.MULTI_EMPRESAS ON REG_FAT.CD_MULTI_EMPRESA = MULTI_EMPRESAS.CD_MULTI_EMPRESA
LEFT JOIN DBAMV.CON_REC ON REG_FAT.CD_REG_FAT = CON_REC.CD_REG_FAT 
                          AND CON_REC.TP_CON_REC = 'P'
                          AND CON_REC.CD_PREVISAO IS NULL
LEFT JOIN DBAMV.ITCON_REC ON CON_REC.CD_CON_REC = ITCON_REC.CD_CON_REC
WHERE REG_FAT.CD_CONVENIO = 304 /*IN (SELECT X.CD_CONVENIO
                                FROM DBAMV.CONVENIO X
                                WHERE X.TP_CONVENIO = 'P')*/
AND Trunc(REG_FAT.DT_INICIO) >= Trunc(To_Date('01/01/2021','DD/MM/YYYY'))
AND Trunc(ATENDIME.DT_ATENDIMENTO) >= Trunc(To_Date('01/01/2020','DD/MM/YYYY'))
AND (CON_REC.CD_CON_REC IS NULL OR
      EXISTS (SELECT 'X'
                FROM DBAMV.ITCON_REC X
                WHERE X.CD_CON_REC = CON_REC.CD_CON_REC
                AND X.TP_QUITACAO IN ('V', 'P', 'C')))

UNION ALL


SELECT  'REG_AMB' TIPO_CONTA
  , Decode(ATENDIME.TP_ATENDIMENTO,'I','INTERNACAO','U','URGENCIA','A','AMBULATORIAL','E','SADT') TP_ATENDIMENTO
  , CASE
      WHEN ATENDIME.CD_CONVENIO <> DADOS_CONTA_AMB.CD_CONVENIO
      THEN 'CONTA EXTRA'
      ELSE 'PARTICULAR'
    END TIPO
  , ORI_ATE.DS_ORI_ATE
  , SETOR.NM_SETOR
  , DADOS_CONTA_AMB.CD_REG_AMB CONTA
  , to_char(ATENDIME.DT_ATENDIMENTO,'dd.mm.yyyy hh24:mi:ss') DT_ATENDIMENTO
  , to_char(ATENDIME.DT_ALTA,'dd.mm.yyyy hh24:mi:ss') DT_ALTA
  , to_char(DADOS_CONTA_AMB.DT_INICIO,'dd.mm.yyyy hh24:mi:ss') DT_INICIO
  , to_char(DADOS_CONTA_AMB.DT_FINAL,'dd.mm.yyyy hh24:mi:ss') DT_FINAL
  , to_char(DADOS_CONTA_AMB.DT_FECHAMENTO,'dd.mm.yyyy hh24:mi:ss') DT_FECHAMENTO
  , DADOS_CONTA_AMB.CD_REMESSA
  , MULTI_EMPRESAS.APELIDO CD_MULTI_EMPRESA
  , DADOS_CONTA_AMB.CD_ATENDIMENTO
  , DADOS_CONTA_AMB.VL_TOTAL_CONTA
  , DADOS_CONTA_AMB.SN_FECHADA
  , CON_REC.CD_CON_REC
  , ITCON_REC.CD_ITCON_REC
  , to_char(ITCON_REC.DT_PREVISTA_RECEBIMENTO,'dd.mm.yyyy hh24:mi:ss')
  , ITCON_REC.TP_QUITACAO
  , ITCON_REC.VL_DUPLICATA
  , ITCON_REC.VL_SOMA_RECEBIDO
  , Nvl(ITCON_REC.VL_DUPLICATA,0) - Nvl(ITCON_REC.VL_SOMA_RECEBIDO,0) VL_EM_ABERTO
  , Round(Nvl(DADOS_CONTA_AMB.DT_FECHAMENTO, SYSDATE) - Nvl(ATENDIME.DT_ALTA, SYSDATE),2) DIAS_DTFINAL_FECHAMENTO
  , Round(Nvl((SELECT Max(PROTOCOLO_DOC.DT_ENVIO)
      FROM DBAMV.PROTOCOLO_DOC
      INNER JOIN DBAMV.IT_PROTOCOLO_DOC ON PROTOCOLO_DOC.CD_PROTOCOLO_DOC = IT_PROTOCOLO_DOC.CD_PROTOCOLO_DOC
      WHERE IT_PROTOCOLO_DOC.CD_REG_AMB = DADOS_CONTA_AMB.CD_REG_AMB
      AND PROTOCOLO_DOC.CD_SETOR_DESTINO = 2
      AND IT_PROTOCOLO_DOC.CD_DOCUMENTO_PROT = 3),SYSDATE)- Nvl(DADOS_CONTA_AMB.DT_FECHAMENTO, SYSDATE) ,2) DIAS_FECHAMENTO_MOVDOC
  , CASE
      WHEN ITCON_REC.DT_PREVISTA_RECEBIMENTO IS NULL
      THEN 'SEM RECEBIMENTO AGENDADO'
      WHEN (SYSDATE - ITCON_REC.DT_PREVISTA_RECEBIMENTO) > 30
      THEN 'INADIMPLENTE'
      ELSE 'PAGAMENTO AGENDADO'
     END STATUS_PAGTO
  , ATENDIME.CD_PACIENTE

FROM DBAMV.ATENDIME
INNER JOIN DBAMV.ORI_ATE ON ATENDIME.CD_ORI_ATE = ORI_ATE.CD_ORI_ATE
INNER JOIN DBAMV.SETOR ON ORI_ATE.CD_SETOR = SETOR.CD_SETOR
INNER JOIN DADOS_CONTA_AMB ON ATENDIME.CD_ATENDIMENTO = DADOS_CONTA_AMB.CD_ATENDIMENTO
INNER JOIN DBAHMD.MULTI_EMPRESAS ON DADOS_CONTA_AMB.CD_MULTI_EMPRESA = MULTI_EMPRESAS.CD_MULTI_EMPRESA
LEFT JOIN DBAMV.CON_REC ON DADOS_CONTA_AMB.CD_REG_AMB = CON_REC.CD_REG_AMB 
                          AND CON_REC.TP_CON_REC = 'P'
                          AND CON_REC.CD_PREVISAO IS NULL
LEFT JOIN DBAMV.ITCON_REC ON CON_REC.CD_CON_REC = ITCON_REC.CD_CON_REC

WHERE Trunc(DADOS_CONTA_AMB.DT_INICIO) >= Trunc(To_Date('01/01/2021','DD/MM/YYYY'))
AND Trunc(ATENDIME.DT_ATENDIMENTO) >= Trunc(To_Date('01/01/2020','DD/MM/YYYY'))
AND (CON_REC.CD_CON_REC IS NULL OR
      EXISTS (SELECT 'X'
                FROM DBAMV.ITCON_REC X
                WHERE X.CD_CON_REC = CON_REC.CD_CON_REC
                AND X.TP_QUITACAO IN ('V', 'P', 'C') ))
 )
"""

QUERY_2 = """
SELECT CD_MULTI_EMPRESA
  , Count(CD_REG_FAT) QTD_CONTAS
  , to_char(MES_ANO,'dd.mm.yyyy hh24:mi:ss') MES_ANO
  , Sum(Nvl(VL_TOTAL_CONTA,0)) VL_TOTAL
FROM(
WITH DADOS_CONTA_AMB
  AS
  (SELECT DISTINCT X.CD_REG_AMB
        , X.CD_ATENDIMENTO
        , Y.DT_LANCAMENTO_FINAL DT_INICIO
        , Y.DT_LANCAMENTO_FINAL DT_FINAL
        , X.DT_FECHAMENTO
        , Y.CD_REMESSA
        , Y.CD_MULTI_EMPRESA
        , Y.VL_TOTAL_CONTA
        , Y.SN_FECHADA
        , Y.CD_CONVENIO
     FROM DBAMV.ITREG_AMB X
     INNER JOIN DBAMV.REG_AMB Y ON X.CD_REG_AMB = Y.CD_REG_AMB
     WHERE Y.CD_CONVENIO = 304 /*IN (SELECT Z.CD_CONVENIO
                                FROM DBAMV.CONVENIO Z
                                WHERE Z.TP_CONVENIO = 'P')*/
  )

SELECT --ATENDIME.TP_ATENDIMENTO
   MULTI_EMPRESAS.APELIDO CD_MULTI_EMPRESA
  , REG_FAT.CD_REG_FAT
  , Trunc(REG_FAT.DT_INICIO,'MM') MES_ANO
  , REG_FAT.VL_TOTAL_CONTA VL_TOTAL_CONTA
FROM DBAMV.ATENDIME
INNER JOIN DBAMV.REG_FAT ON ATENDIME.CD_ATENDIMENTO = REG_FAT.CD_ATENDIMENTO
INNER JOIN DBAHMD.MULTI_EMPRESAS ON REG_FAT.CD_MULTI_EMPRESA = MULTI_EMPRESAS.CD_MULTI_EMPRESA
WHERE REG_FAT.CD_CONVENIO = 304 /*IN (SELECT X.CD_CONVENIO
                                FROM DBAMV.CONVENIO X
                                WHERE X.TP_CONVENIO = 'P')*/
AND Trunc(REG_FAT.DT_INICIO) >= Trunc(To_Date('01/01/2021','DD/MM/YYYY'))
--GROUP BY REG_FAT.CD_MULTI_EMPRESA, Trunc(REG_FAT.DT_INICIO,'MM')

UNION ALL

SELECT MULTI_EMPRESAS.APELIDO CD_MULTI_EMPRESA
  , DADOS_CONTA_AMB.CD_REG_AMB
  , Trunc(DADOS_CONTA_AMB.DT_INICIO, 'MM') MES_ANO
  , DADOS_CONTA_AMB.VL_TOTAL_CONTA VL_TOTAL_CONTA
FROM DBAMV.ATENDIME
INNER JOIN DADOS_CONTA_AMB ON ATENDIME.CD_ATENDIMENTO = DADOS_CONTA_AMB.CD_ATENDIMENTO
INNER JOIN DBAHMD.MULTI_EMPRESAS ON DADOS_CONTA_AMB.CD_MULTI_EMPRESA = MULTI_EMPRESAS.CD_MULTI_EMPRESA
WHERE Trunc(DADOS_CONTA_AMB.DT_INICIO) >= Trunc(To_Date('01/01/2021','DD/MM/YYYY'))
--GROUP BY DADOS_CONTA_AMB.CD_MULTI_EMPRESA, Trunc(DADOS_CONTA_AMB.DT_INICIO,'MM')

)
GROUP BY CD_MULTI_EMPRESA, MES_ANO
"""